obj-$(CONFIG_KRG_SCHED_ECHO_POLICY) += echo_policy.o

obj-$(CONFIG_KRG_SCHED_MOSIX_LOAD_BALANCER) += mosix_load_balancer.o
obj-$(CONFIG_KRG_SCHED_ROUND_ROBIN_BALANCER) += round_robin_balancer.o
obj-$(CONFIG_KRG_SCHED_RBT_POLICY) += rbt_policy.o

EXTRA_CFLAGS += -Wall -Werror
