obj-$(CONFIG_KRG_SCHED_THRESHOLD_FILTER) += threshold_filter.o
obj-$(CONFIG_KRG_SCHED_FREQ_LIMIT_FILTER) += freq_limit_filter.o
obj-$(CONFIG_KRG_SCHED_REMOTE_CACHE_FILTER) += remote_cache_filter.o
obj-$(CONFIG_KRG_SCHED_RBT_CACHE_FILTER) += rbt_cache_filter.o

EXTRA_CFLAGS += -Wall -Werror
