obj-$(CONFIG_KRG_SCHED_HIGH_THRESHOLD_FILTER) += high_threshold_filter.o
obj-$(CONFIG_KRG_SCHED_LOW_THRESHOLD_FILTER) += low_threshold_filter.o
obj-$(CONFIG_KRG_SCHED_FREQ_LIMIT_FILTER) += freq_limit_filter.o
obj-$(CONFIG_KRG_SCHED_REMOTE_CACHE_FILTER) += remote_cache_filter.o
obj-$(CONFIG_KRG_SCHED_DIFF_FILTER) += diff_filter.o
obj-$(CONFIG_KRG_SCHED_CONSTANT_FILTER) += constant_filter.o

EXTRA_CFLAGS += -Wall -Werror
