obj-$(CONFIG_KRG_SCHED_CPU_PROBE) += cpu_probe.o
obj-$(CONFIG_KRG_SCHED_MEM_PROBE) += mem_probe.o

obj-$(CONFIG_KRG_SCHED_MIGRATION_PROBE) += migration_probe.o
obj-$(CONFIG_KRG_SCHED_MOSIX_PROBE) += mosix_probe.o

obj-$(CONFIG_KRG_SCHED_CPUSPEED_PROBE) += cpuspeed_probe.o
obj-$(CONFIG_KRG_SCHED_LOAD_PROBE) += load_probe.o
obj-$(CONFIG_KRG_SCHED_PROCESSSIZE_PROBE) += processsize_probe.o
obj-$(CONFIG_KRG_SCHED_LOCAL_USER_NOTIFIER) += local_user_notifier.o
obj-$(CONFIG_KRG_SCHED_LOCAL_USER_PRESENCE) += local_user_presence.o
obj-$(CONFIG_KRG_SCHED_USER_PROBE) += user_probe.o
obj-$(CONFIG_KRG_SCHED_MATTLOAD_PROBE) += mattload_probe.o

EXTRA_CFLAGS += -Werror -Wall
