
obj-$(CONFIG_KRG_HOTPLUG) += hotplug/
obj-$(CONFIG_KRG_CAP) += capability/
obj-$(CONFIG_KRG_PROCFS) += procfs/
obj-$(CONFIG_KRG_PROC) += proc/
obj-$(CONFIG_KRG_DVFS) += fs/
obj-$(CONFIG_KRG_EPM) += epm/ ghost/
obj-$(CONFIG_KRG_MM) += mm/
obj-$(CONFIG_KRG_SCHED) += scheduler/
