
obj-y	:= hotplug/
obj-$(CONFIG_KRG_CAP) += capability/
obj-$(CONFIG_KRG_PROCFS) += procfs/
obj-$(CONFIG_KRG_PROC) += proc/
obj-$(CONFIG_KRG_DVFS) += fs/
obj-$(CONFIG_KRG_FAF) += fs/faf/
obj-$(CONFIG_KRG_EPM) += epm/ ghost/ epm/application/
