#
# Makefile for the Linux TIPC layer
#

obj-$(CONFIG_TIPC) := tipc.o

tipc-y	+= tipc_addr.o tipc_bcast.o tipc_bearer.o tipc_cfgsrv.o  \
	   tipc_core.o tipc_handler.o tipc_link.o tipc_discover.o tipc_msg.o  \
	   tipc_name_distr.o tipc_topsrv.o tipc_name_table.o tipc_net.o  \
	   tipc_netlink.o tipc_node.o tipc_port.o tipc_ref.o  \
	   tipc_socket.o tipc_user_reg.o tipc_dbg.o tipc_eth_media.o

# End of file
